# Site settings
title: Eventacular
description: "Eventacular is a Tokyo-based startup company that is developing an online platform to help event organizers sell tickets to their events."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eventacular.net" # the name of your domain
logo_url: img/eventacular-logo-light-bg@3x.png

# Hero
hero:
    hero_img: conference.jpg
    hero_title: Eventacular
    hero_description: Eventacular is a Tokyo-based startup company that is developing an online platform to help event organizers sell tickets to their events.

# Contact form
api_token: "f38d65b370b6c89ea94f68521464b03c"

# Contact info
contact:
    phone:
    emergency:
    email: team@eventacular.com
    address: Yahoo Lodge 17F<br />Tokyo Garden Terrace Kioicho<br />Kioicho 1-3, Chiyoda-ku<br />Tokyo, Japan

# Opening hours
monday_friday: 10:00 – 19:00
saturday_sunday: closed
public_holidays: closed

# Testimonials
testimonials:
    testimonials_img: landing-page-small.jpg

# Map
map:
    zoom: 15
    address: Tokyo, Chiyoda-ku, Kioicho 1-2
    address_details: img/eventacular-logo-tiny.png

# Social settings
facebook: https://www.facebook.com/eventacular
twitter: https://twitter.com/eventacular
instagram: https://www.instagram.com/eventacular/
youtube: no
skype: no
feed: no

# Footer
copyright: © 2017 Eventacular KK

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: UA-10455567-16
google_verification:
